---
title: "p8105_HW1_mk4208"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading packages

```{r}
library(tidyverse)
```


Problem 1 

```{r}
# Creating a data frame

set.seed(100)
df = tibble(
  random = rnorm(8),
  vec_logical = random > 0,
  vec_char = c("a", "b", "c", "e", "f", "g", "h", "i"),
  vec_factor = factor(c(1, 2, 3, 1, 2, 3, 1, 2))
)

# Taking the mean of each variable in the dataframe 
mean(pull(df, random)) # WORKS 
mean(pull(df, vec_logical)) # WORKS
mean(pull(df, vec_char)) # Does not work
mean(pull(df, vec_factor)) # Does not work
```

```{r}
# Writing a code chunk that applies as.numeric function to the logical, character, and factor variables 

mean(as.numeric(pull(df, vec_logical)))
mean(as.numeric(pull(df, vec_char)))
mean(as.numeric(pull(df, vec_factor)))
```

```{r}
# Converting the logical vector to numeric and multiplying the random sample by the result 

as.numeric(pull(df, vec_logical)) * pull(df, random)

# Converting the logical vector to a factor and multiplying the random sample by the result 

as.factor(pull(df, vec_logical)) * pull(df, random)

# Converting the logical vector to a factor and then converting the result to numberic and multiplying the random sample by the result 

as.numeric(as.factor(pull(df, vec_logical))) * pull(df, random)

```

Problem 2 

```{r}
# Creating a data frame 
df2 = tibble(
  x = rnorm(500),
  y = rnorm(500),
  vec_logical = x + y > 1,
  vec_numeric = as.numeric(vec_logical),
  vec_factor = as.factor(vec_logical)
)
```

Here is a short description of the dataframe created: 
This dataframe has `r nrow(df2)` rows and `r ncol(df2)` columns. 
The mean, median and standard deviation of 'x' variable is `r mean(pull(df2, x))`, `r median(pull(df2, x))`, and `r sd(pull(df2, x))` respectively. The proportion of cases with x + y > 1 is `r mean(pull(df2, x))` 

```{r}
# Creating a scatter plot of  y vs x 
plot1 = ggplot(df2, aes(x=x, y=y, color=vec_logical)) + 
  geom_point()

print(plot1)

plot2 = ggplot(df2, aes(x=x, y=y, color=vec_numeric)) + 
  geom_point()

print(plot2)

plot3 = ggplot(df2, aes(x=x, y=y, color=vec_factor)) + 
  geom_point()

print(plot3)
```



